language: node_js
node_js:
    - "4.1"
after_success:
  - npm run-script coveralls
  - npm run-script build
deploy:
  provider: script
  skip_cleanup: true
  script: scripts/deploy.sh
  on:
    tags: true
