language: node_js
node_js:
    - "4.1"
after_success:
  - npm run-script coveralls
  - npm run-script build
deploy:
  provider: npm
  email: "mookjpy@gmail.com"
  api_key: $NPM_API_KEY
  skip_cleanup: true
  on:
    tags: true
